services:
  stats-server:
    build: ./ewm-stats-server/stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=ewm_stats
    ports:
      - "6543:5432"

  ewm-service:
    build: ./ewm-main-server
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=ewm_main
    ports:
      - "6542:5432"