CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL,
    name varchar(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation varchar(2000) NOT NULL,
    category_id BIGINT NOT NULL REFERENCES categories (id),
    confirmed_requests int NOT NULL,
    created_on timestamp NOT NULL,
    description varchar(7000) NOT NULL,
    event_date timestamp NOT NULL,
    initiator_id BIGINT NOT NULL REFERENCES users (id),
    location_lat FLOAT NOT NULL,
    location_lon FLOAT NOT NULL,
    paid bool NOT NULL,
    participant_limit int NOT NULL,
    published_on timestamp NOT NULL,
    request_moderation bool NOT NULL,
    state varchar(50) NOT NULL,
    title varchar(255) NOT NULL,
    views int NOT NULL
);
CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date timestamp NOT NULL,
    event_id BIGINT NOT NULL REFERENCES events(id),
    requester_id BIGINT NOT NULL REFERENCES users(id),
    status varchar(50) NOT NULL
);